# Basic
title: Zeng Fan
subtitle: Back End
welcome_message: <a href="https://github.com/zengfann/zengfann.github.io" target="_blank">访问个人Github</a>
description: 风暴终将我们吹散
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://zengfann.github.io"
permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: empty

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog
about_button:
    title: About
    description: Introduce me
life_button:
    title: Life 
    description: Dadily Life
friends_button:
    title: Friends
    description: Friend's Blog
# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.zengfann.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment

comment:
    disqus: zengfann
    # duoshuo: true

# Social
social:
    weibo: 需冷藏
    github: zengfann
    twitter: Summer_zf
    gplus: 107108267983477358170
    mail: zf2420840650@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
